apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-service-1
  name: customer-service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customer-service-1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: customer-service-1
    spec:
      containers:
        - image: sahanan05/customer_service_1:latest
          name: customer-service-1
          ports:
            - containerPort: 8080
          resources: {}
      hostname: customer-service-1
      restartPolicy: Always
status: {}
