apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: order-service-2
  name: order-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-service-2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: order-service-2
    spec:
      containers:
        - image: sahanan05/order_service_2:latest
          name: order-service-2
          ports:
            - containerPort: 8081
          resources: {}
      hostname: order-service-2
      restartPolicy: Always
status: {}
